# neovim and required packages
brew "python"
brew "neovim"
brew "lazygit"
brew "ripgrep"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "fzf"
brew "fd"
brew "luarocks"

# misc
brew "bat"
brew "gh"
brew "mise"
brew "tldr"
brew "tmux"
brew "dockutil"
brew "shellcheck"
brew "trash"
brew "zoxide"

# ohmyzsh
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
